### ISSUE TITLE
Some options have to be set globaly and localy

### ISSUE THREAD

**Issue by leiserfg** [tsbohc/zest.nvim#1] opened 2021-05-13 12:36 UTC
As you can see in
https://github.com/nanotee/nvim-lua-guide#caveats-3
that makes it impossible to use zest to configure `number` or `relativenumber`.
It works if you always set the global option and the local (buffer or window) option optioned from the scope.

**Comment by tsbohc** [comment] 2021-05-13 16:39
Hmm, I can't reproduce that, at least not with `number` and `relativenumber`.
```lua
:lua vim.api.nvim_win_set_option(0, "number", true)
:lua vim.api.nvim_win_set_option(0, "relativenumber", true)
```
In `nvim --clean` sets both options, and they remain active for new buffers, windows, tabs, etc.

I am running `NVIM v0.5.0-dev+1233-g82ac44d01`.

**Comment by tsbohc** [comment] 2021-05-13 17:03
Okay, I got it. This is definitely happening with `shiftwidth` and `expandtab`, which seem to be set only in the first buffer after opening neovim.

I will not be making any changes, as I'm hoping neovim/neovim#13479 will be merged soon. After that, `se-` will wrap the new api.

For now, I will include a warning in the readme.

**Closed by tsbohc** 2021-05-13 17:03 UTC
